version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/register_with_elb.sh
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/deregister_from_elb.sh
    - location: Scripts/stop_server.sh
      timeout: 300
      runas: root
